stages: [build]

variables:
  DOCKERFILE: Dockerfile
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

build_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]                # правильное место для entrypoint
  tags: ["main"]
  variables:
    DOCKER_CONFIG: /kaniko/.docker
    # Убедись, что эти переменные есть в проекте (или GitLab CE их подставляет сам):
    # CI_REGISTRY: "192.168.0.10:5050"
    # CI_REGISTRY_IMAGE: "192.168.0.10:5050/<group>/app"
    # CI_REGISTRY_USER: "<deploy-user>"
    # CI_REGISTRY_PASSWORD: "<deploy-token>"
  script:
    - mkdir -p "$DOCKER_CONFIG"
    - printf '{"auths":{"%s":{"username":"%s","password":"%s"}}}\n' \
        "$CI_REGISTRY" "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD" > "$DOCKER_CONFIG/config.json"
    # ВАЖНО: один shell-стейтмент. Используем YAML '>' чтобы склеить аргументы в одну строку
    - >
      /kaniko/executor
      --context "$CI_PROJECT_DIR"
      --dockerfile Dockerfile
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
      --insecure
      --skip-tls-verify
  rules:
    - if: $CI_COMMIT_BRANCH

smoke:
  stage: build
  image: alpine:3.20
  tags: ["main"]
  script:
    - echo "runner OK"
    - uname -a
